# FROM node:alpine3.23
# WORKDIR /app
# COPY . .
# RUN npm install 
# EXPOSE 5173
# CMD ["npm", "run", "dev", "--", "--host"]

FROM node:alpine3.23 as builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
